# File: environment.yml
# Created Date: Saturday February 13th 2021
# Author: Steven Atkinson (steven@atkinson.mn)

# Environment for CPU and macOS (Intel and Apple Silicon)

name: nam
channels:
  - conda-forge # pytest-mock
  - defaults
dependencies:
  - python>=3.9
  - black
  - flake8
  - h5py
  - jupyter
  - matplotlib
  - numpy<2
  - pip
  - pre-commit
  - pydantic
  - pytest
  - pytest-mock
  - semver
  - tensorboard
  - tqdm
  - wheel
  - pip:
      - auraloss==0.3.0
      - pytorch_lightning
      - sounddevice
      - transformers>=4  # See requirements.txt
      - wavio >=0.0.5
      - -e ..
      - torch
